# Generated by Django 4.0.3 on 2024-05-20 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0005_alter_employee_gender_orderofservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderofservice',
            name='stattus',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('resolvido', 'Resolvido')], default='aberto', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderofservice',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eqrApp.employee', verbose_name='Equipamento:'),
        ),
    ]
