# Generated by Django 4.0.3 on 2024-05-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqrApp', '0006_orderofservice_stattus_alter_orderofservice_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderofservice',
            name='stattus',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('resolvido', 'Resolvido')], default='Aberto', max_length=50),
        ),
    ]
